Repository cloudposse/terraform-aws-ec2-instance, pull requests merged in 2024-03, with the labels that each got.

#186 Update Scaffolding
  .github/mergify.yml
  README.md
  README.yaml
Labels: auto-update, no-release, do not merge, migration

#187 Add GitHub Settings
  .github/settings.yml
Labels: auto-update, no-release, migration

#173 Remove optional `domain` attribute from `aws_eip` resource
  eni.tf
  main.tf
Labels: patch

#190 Add tags to additional eip
  eni.tf
Labels: enhancement, minor
